// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: ficsithub.proto

package ficsithub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ficsithub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ficsithub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ficsithub_proto_rawDescGZIP(), []int{0}
}

type PioneersList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pioneers []*Pioneer `protobuf:"bytes,1,rep,name=pioneers,proto3" json:"pioneers,omitempty"`
}

func (x *PioneersList) Reset() {
	*x = PioneersList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ficsithub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PioneersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PioneersList) ProtoMessage() {}

func (x *PioneersList) ProtoReflect() protoreflect.Message {
	mi := &file_ficsithub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PioneersList.ProtoReflect.Descriptor instead.
func (*PioneersList) Descriptor() ([]byte, []int) {
	return file_ficsithub_proto_rawDescGZIP(), []int{1}
}

func (x *PioneersList) GetPioneers() []*Pioneer {
	if x != nil {
		return x.Pioneers
	}
	return nil
}

type Pioneer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Pioneer) Reset() {
	*x = Pioneer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ficsithub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pioneer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pioneer) ProtoMessage() {}

func (x *Pioneer) ProtoReflect() protoreflect.Message {
	mi := &file_ficsithub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pioneer.ProtoReflect.Descriptor instead.
func (*Pioneer) Descriptor() ([]byte, []int) {
	return file_ficsithub_proto_rawDescGZIP(), []int{2}
}

func (x *Pioneer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_ficsithub_proto protoreflect.FileDescriptor

var file_ficsithub_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x63, 0x73, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x69,
	0x6f, 0x6e, 0x65, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x69,
	0x6f, 0x6e, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50,
	0x69, 0x6f, 0x6e, 0x65, 0x65, 0x72, 0x52, 0x08, 0x70, 0x69, 0x6f, 0x6e, 0x65, 0x65, 0x72, 0x73,
	0x22, 0x25, 0x0a, 0x07, 0x50, 0x69, 0x6f, 0x6e, 0x65, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x36, 0x0a, 0x09, 0x46, 0x69, 0x63, 0x73, 0x69,
	0x74, 0x48, 0x75, 0x62, 0x12, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x69,
	0x6f, 0x6e, 0x65, 0x65, 0x72, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d,
	0x2e, 0x50, 0x69, 0x6f, 0x6e, 0x65, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x63, 0x73, 0x69, 0x74, 0x68, 0x75, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ficsithub_proto_rawDescOnce sync.Once
	file_ficsithub_proto_rawDescData = file_ficsithub_proto_rawDesc
)

func file_ficsithub_proto_rawDescGZIP() []byte {
	file_ficsithub_proto_rawDescOnce.Do(func() {
		file_ficsithub_proto_rawDescData = protoimpl.X.CompressGZIP(file_ficsithub_proto_rawDescData)
	})
	return file_ficsithub_proto_rawDescData
}

var file_ficsithub_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ficsithub_proto_goTypes = []interface{}{
	(*Empty)(nil),        // 0: Empty
	(*PioneersList)(nil), // 1: PioneersList
	(*Pioneer)(nil),      // 2: Pioneer
}
var file_ficsithub_proto_depIdxs = []int32{
	2, // 0: PioneersList.pioneers:type_name -> Pioneer
	0, // 1: FicsitHub.GetAllPioneers:input_type -> Empty
	1, // 2: FicsitHub.GetAllPioneers:output_type -> PioneersList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ficsithub_proto_init() }
func file_ficsithub_proto_init() {
	if File_ficsithub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ficsithub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ficsithub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PioneersList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ficsithub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pioneer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ficsithub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ficsithub_proto_goTypes,
		DependencyIndexes: file_ficsithub_proto_depIdxs,
		MessageInfos:      file_ficsithub_proto_msgTypes,
	}.Build()
	File_ficsithub_proto = out.File
	file_ficsithub_proto_rawDesc = nil
	file_ficsithub_proto_goTypes = nil
	file_ficsithub_proto_depIdxs = nil
}
